<?php

namespace Core\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	function findAdmins(){
		// Querying for Objects Using Doctrine's Query Builder
		$qb = $this->createQueryBuilder('u')
			->where('u.roles LIKE :role')
			->setParameter('role', '%"ROLE_ADMIN"%')
			->getQuery();

		//Querying for Objects with DQL
		// $qb = $this->getEntityManager()->createQuery(
		// 	'SELECT u
		// 	 FROM UserBundle:User u 
		// 	 WHERE u.roles LIKE :role'
		// 	)->setParameter('role', '%"ROLE_ADMIN"%')

		return $qb->getResult();
	}

	function findUsers(){
		// Querying for Objects Using Doctrine's Query Builder
		$qb = $em->createQueryBuilder('u')
			->where('u.roles NOT LIKE :role')
			->setParameter('role', '%"ROLE_ADMIN"%')
			->getQuery();

		return $qb->getResult();
	}
}
